import type { Metadata } from "next";
import "../globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header />
          <div>
            <div className="max-w-7xl min-h-screen mx-auto py-12 px-5">
              {children}
            </div>
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
